config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  post "/home/save" => 'home#save', as: "save_game"
  get "/home/delete_cookies" => 'home#delete_cookies', as: "delete_cookies"

  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :parent, class_name: Item, foreign_key: :parent_id
	has_many :children, class_name: Item, foreign_key: :parent_id

	def self_and_parents
		if parent_id
			[self, self.parent.self_and_parents].flatten
		else
			self
		end
	end

	def self.filtered_list text
		Item.where("name like ?", "%#{text}%").map do |i|
			i.self_and_parents
		end.flatten
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		if cookies.signed[:game_data]
			@game_data = JSON.parse cookies.signed[:game_data]
			@money = @game_data.delete "money"
		else
			@game_data = {iron: {"max_miners" => 10}, copper: {}, silver: {}, gold: {}, diamond: {}, platinum: {}, obsidian: {}, emerald: {}, sapphire: {}, ruby: {}}
			@money = 0
		end
	end

	def save
		cookies.signed.permanent[:game_data] = params[:game_data].symbolize_keys.to_json
		render text: params[:message] || "Game Saved"
	end

	def delete_cookies
		cookies.delete :game_data
		redirect_to :root
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	def index
		if params[:search]
			@filtered_items = Item.filtered_list(params[:search])
			puts @filtered_items
		end
		@root_items = Item.where(parent_id: nil)
	end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

	def filtered_subtree(item)
		if @filtered_items
			subtree(item) if @filtered_items.include? item
		else
			subtree(item)	
		end
	end

	def subtree(item)
		ret = "<li>#{item.name}"
		item.children.each do |child|
			ret += "<ul>#{filtered_subtree(child)}</ul>"
		end if item.children
		ret += "</li>"
		ret.html_safe
	end

end

app/views/home/index.haml
%h1 ruby miner v0.1
.main_btns
	= link_to "delete cookies", delete_cookies_path, class: "btn"
	= link_to "money cheat", "#", class: "money_cheat btn"
	= link_to "save", "#", class: "save_game btn"

%hr

#stats
	%table
		%thead
			%tr.headers
				%th ore
				%th in inventory
				%th miners
				%th max_miners
				%th total value
				%th action
		%tbody
			- @game_data.each_pair do |name, ore_data|
				%tr{class: name}
					%td= name
					%td.amount= ore_data["amount"].to_i
					%td.miners= ore_data["miners"].to_i
					%td.max_miners= ore_data["max_miners"].to_i
					%td.value
					%td
						= link_to "hire", '#', class: "hire btn"
						= link_to "sell", '#', class: "sell btn"
			%tr.money
				%td
					money: 
					%span.value= @money
				%td
				%td
				%td
				%td.total_value
				%td= link_to "sell_all", "#", class: "btn"

%hr

#rocks
	- @game_data.keys.each do |name|
		.ore{class: "#{name} raven"}= name

app/views/items/index.haml
%h1 items
= form_tag :items, method: :get do
	= text_field_tag :search
	= submit_tag "search!"
	
%ul
	- @root_items.each do |root_item|
		= filtered_subtree(root_item)

app/views/layouts/application.haml
!!!
%html
	%head
		%title Game
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		.wrapper
			%br
			= yield
			.push
		%footer
			%hr{style: "clear:both"}
			.footer-text
				%span.raven wicked-raven
			#notification{style: "display:none"}
				Game Saved